export default {
  name: 'testimonial',
  title: 'Témoignages',
  type: 'document',
  fields: [
    {
      name: 'clientName',
      title: 'Nom du client',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'avatarType',
      title: "Type d'avatar",
      type: 'string',
      options: {
        list: [
          {title: 'Personnes neutres', value: 'personas'},
          {title: 'Bot neutre', value: 'bottts'},
          {title: 'Identicon', value: 'identicon'},
          {title: 'Avataaars', value: 'avataaars'},
          {title: 'Jdenticon', value: 'jdenticon'},
          {title: 'Gridy', value: 'gridy'},
          {title: 'Micah', value: 'micah'},
          {title: 'Fun Emoji', value: 'fun-emoji'},
          {title: 'Big Smile', value: 'big-smile'},
          {title: 'Croodles', value: 'croodles'},
          {title: 'Croodles Neutre', value: 'croodles-neutral'},
          {title: 'Comic', value: 'comic'},
          {title: 'Sunny', value: 'sunny'},
          {title: 'Ring', value: 'ring'},
          {title: 'Beam', value: 'beam'},
          {title: 'Wave', value: 'wave'},
          {title: 'Bauhaus', value: 'bauhaus'},
          {title: 'Pixel Art', value: 'pixel-art'},
          {title: 'Lorelei', value: 'lorelei'},
          {title: 'Lorelei Neutre', value: 'lorelei-neutral'},
          {title: 'Notionists', value: 'notionists'},
          {title: 'Notionists Neutre', value: 'notionists-neutral'},
          {title: 'Shapes', value: 'shapes'},
          {title: 'Marble', value: 'marble'},
          {title: 'Cat', value: 'cat'},
          {title: 'Miniavs', value: 'miniavs'},
          {title: 'Thumbs', value: 'thumbs'},
          {title: 'Mosaic', value: 'mosaic'},
          {title: 'Adventurer', value: 'adventurer'},
          {title: 'Adventurer Neutre', value: 'adventurer-neutral'},
          {title: 'Big Ears', value: 'big-ears'},
          {title: 'Big Ears Neutre', value: 'big-ears-neutral'},
          {title: 'Lily', value: 'lily'},
          {title: 'Lily Neutre', value: 'lily-neutral'},
          {title: 'Personas Neutre', value: 'personas-neutral'},
        ],
        layout: 'dropdown',
      },
      validation: (Rule: any) => Rule.required(),
      description: "Choisissez un style d'avatar non genré",
    },
    {
      name: 'avatarSeed',
      title: "Seed pour l'avatar",
      type: 'string',
      description:
        "Texte unique pour générer l'avatar (nom, email, etc.). Laissez vide pour utiliser le nom du client.",
      validation: (Rule: any) => Rule.max(50),
    },
    {
      name: 'testimonial',
      title: 'Témoignage',
      type: 'text',
      rows: 4,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'rating',
      title: 'Note',
      type: 'number',
      validation: (Rule: any) => Rule.required().min(1).max(5),
      description: 'Note sur 5 étoiles',
    },
    {
      name: 'date',
      title: 'Date',
      type: 'date',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'order',
      title: "Ordre d'affichage",
      type: 'number',
      description: 'Ordre dans la liste des témoignages (1 = premier)',
    },
  ],

  preview: {
    select: {
      title: 'clientName',
      rating: 'rating',
      date: 'date',
      avatarType: 'avatarType',
    },
    prepare(selection: any) {
      const {rating, date, avatarType} = selection
      return {
        ...selection,
        subtitle: `${rating}/5 - ${new Date(date).toLocaleDateString('fr-FR')} - ${avatarType}`,
      }
    },
  },
}
